import {
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Atom,
  Binary,
  Boxes,
  Braces,
  CircleCheck,
  CircleDot,
  Component,
  Copy,
  Cpu,
  Database,
  DatabaseZap,
  Facebook,
  FileCheck2,
  FileCode2,
  FileDown,
  FlaskConical,
  GitBranch,
  Github,
  GitMerge,
  GraduationCap,
  Hexagon,
  Info,
  LayoutDashboard,
  Lightbulb,
  Linkedin,
  ListChecks,
  LockKeyhole,
  Mail,
  MapPin,
  MessagesSquare,
  MonitorSmartphone,
  Moon,
  MousePointer2,
  Palette,
  PanelsTopLeft,
  Phone,
  Play,
  Plus,
  RadioTower,
  Send,
  Server,
  ServerCog,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Sun,
  TableProperties,
  Telescope,
  Waypoints,
  Workflow,
  X,
} from "lucide-react";

const icons = {
  "arrow-down-right": ArrowDownRight,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  atom: Atom,
  binary: Binary,
  boxes: Boxes,
  braces: Braces,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  component: Component,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  "database-zap": DatabaseZap,
  facebook: Facebook,
  "file-check-2": FileCheck2,
  "file-code-2": FileCode2,
  "file-down": FileDown,
  "flask-conical": FlaskConical,
  "git-branch": GitBranch,
  github: Github,
  "git-merge": GitMerge,
  "graduation-cap": GraduationCap,
  hexagon: Hexagon,
  info: Info,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  linkedin: Linkedin,
  "list-checks": ListChecks,
  "lock-keyhole": LockKeyhole,
  mail: Mail,
  "map-pin": MapPin,
  "messages-square": MessagesSquare,
  "monitor-smartphone": MonitorSmartphone,
  moon: Moon,
  "mouse-pointer-2": MousePointer2,
  palette: Palette,
  "panels-top-left": PanelsTopLeft,
  phone: Phone,
  play: Play,
  plus: Plus,
  "radio-tower": RadioTower,
  send: Send,
  server: Server,
  "server-cog": ServerCog,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sun: Sun,
  "table-properties": TableProperties,
  telescope: Telescope,
  waypoints: Waypoints,
  workflow: Workflow,
  x: X,
};

export default function Icon({ name, ...props }) {
  const LucideIcon = icons[name];
  if (!LucideIcon) return null;
  return (
    <LucideIcon
      aria-hidden="true"
      focusable="false"
      strokeWidth={1.8}
      {...props}
    />
  );
}
